project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "TBIP (beta)"
  favicon: favicon.webp
  navbar:
    left:
      - href: speeches/index.qmd
        text: Floor Speeches
      - href: twitter/index.qmd
        text: Twitter
      - href: methodology/index.qmd
        text: Methodology
  page-footer:
    left: "Maintained by [SoRelle W. Gaynor](https://sorellewg.com), University of Virginia"
    right: "Questions? [sorellewg@virginia.edu](mailto:sorellewg@virginia.edu)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: full
    