---
title: "Papers"
---

### "Express Yourself (Ideologically): Legislators' Ideal Points Across Audiences"

Gaynor, S. W., Miler, K., Goel, P., Hoyle, A. M., and Resnik, P. (2026). *Journal of Politics*, 88(4). [https://doi.org/10.1086/736360](https://doi.org/10.1086/736360)

Members of Congress face consistent pressure—and ample opportunity—to express their ideological positions. The most commonly measured outlet is congressional floor votes, but it is not the only one. This research develops three novel ideal point measures across different ideological expressions—votes, floor speeches, and tweets—to capture the understudied interaction between ideology, communication style, and audience. We find that legislators use speech and tweets to convey nuance in their ideological positions and to differentiate themselves from other members of their party in ways that voting does not allow. In general, Republicans use text-based opportunities, particularly Twitter, to express more conservative positions, while Democratic positioning is dependent on a legislator’s district and personal attributes. In both theory and methods, this work engages the considerable literature on the measurement of ideology and congressional representation. This research contributes to our understanding of legislator behavior and ideological positioning and introduces three replicable ideal point models to measure the ideology of members of the US Congress.
[PDF](files/Gaynoretal_ExpressYourself_JOP2026.pdf)